// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.5
// source: mo.proto

package taitung_mod

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoadFileModuleInterface_StoreLogAbsPath_FullMethodName = "/mod_proto.LoadFileModuleInterface/StoreLogAbsPath"
)

// LoadFileModuleInterfaceClient is the client API for LoadFileModuleInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoadFileModuleInterfaceClient interface {
	StoreLogAbsPath(ctx context.Context, in *FilePathBufRequest, opts ...grpc.CallOption) (*FilePathBufResponse, error)
}

type loadFileModuleInterfaceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoadFileModuleInterfaceClient(cc grpc.ClientConnInterface) LoadFileModuleInterfaceClient {
	return &loadFileModuleInterfaceClient{cc}
}

func (c *loadFileModuleInterfaceClient) StoreLogAbsPath(ctx context.Context, in *FilePathBufRequest, opts ...grpc.CallOption) (*FilePathBufResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilePathBufResponse)
	err := c.cc.Invoke(ctx, LoadFileModuleInterface_StoreLogAbsPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoadFileModuleInterfaceServer is the server API for LoadFileModuleInterface service.
// All implementations must embed UnimplementedLoadFileModuleInterfaceServer
// for forward compatibility.
type LoadFileModuleInterfaceServer interface {
	StoreLogAbsPath(context.Context, *FilePathBufRequest) (*FilePathBufResponse, error)
	mustEmbedUnimplementedLoadFileModuleInterfaceServer()
}

// UnimplementedLoadFileModuleInterfaceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoadFileModuleInterfaceServer struct{}

func (UnimplementedLoadFileModuleInterfaceServer) StoreLogAbsPath(context.Context, *FilePathBufRequest) (*FilePathBufResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreLogAbsPath not implemented")
}
func (UnimplementedLoadFileModuleInterfaceServer) mustEmbedUnimplementedLoadFileModuleInterfaceServer() {
}
func (UnimplementedLoadFileModuleInterfaceServer) testEmbeddedByValue() {}

// UnsafeLoadFileModuleInterfaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoadFileModuleInterfaceServer will
// result in compilation errors.
type UnsafeLoadFileModuleInterfaceServer interface {
	mustEmbedUnimplementedLoadFileModuleInterfaceServer()
}

func RegisterLoadFileModuleInterfaceServer(s grpc.ServiceRegistrar, srv LoadFileModuleInterfaceServer) {
	// If the following call pancis, it indicates UnimplementedLoadFileModuleInterfaceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoadFileModuleInterface_ServiceDesc, srv)
}

func _LoadFileModuleInterface_StoreLogAbsPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilePathBufRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadFileModuleInterfaceServer).StoreLogAbsPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadFileModuleInterface_StoreLogAbsPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadFileModuleInterfaceServer).StoreLogAbsPath(ctx, req.(*FilePathBufRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoadFileModuleInterface_ServiceDesc is the grpc.ServiceDesc for LoadFileModuleInterface service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoadFileModuleInterface_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mod_proto.LoadFileModuleInterface",
	HandlerType: (*LoadFileModuleInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreLogAbsPath",
			Handler:    _LoadFileModuleInterface_StoreLogAbsPath_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mo.proto",
}
